### ISSUE TITLE
Erro no handle callback

### ISSUE THREAD

**Issue by marcoblos** [MastercardBR/exemplo-masterpass-java-web#1]
Segui os procedimentos tanto aqui do .MD do projeto quanto dos links passados para o site da Mastercard, realizei diversos testes, porém a linha `Card c = t.getCard(req.queryParams("oauth_verifier"));` do método `StandardCheckoutController.handleCallback` responsável por realizar algumas transações de confirmação pelo o que entendi, ao ser chamada chama alguns métodos do SDK da Mastercard, eu acho, resultando no seguinte erro:

```
class Errors {
    error: [class Error {
        description: The request contains an incomplete or invalid oauth_signature.
        reasonCode: AUTHENTICATION_FAILED
        recoverable: false
        source: OAuth.Signature
        details: class Details {
            detail: [class Detail {
                name: Allowed OAuth Signature Base String 1
                value: <![CDATA[
                GET&https%3A%2F%2Fsandbox.api.mastercard.com%2Fmasterpass%2Fpaymentdata%2Fcc2467bd62e8a69cefdf4638083cabc2fe3ae43a&cartId%3D21345%26checkoutId%3D512135f929c448d0b930b537c1426ee2%26oauth_consumer_key%3Dx9CN7cXABdzeOpjVrAOa7v4pHhpkzLNTDcMEIOY60e2a0e46%252110e8bc47714141be983e984732a73a4c0000000000000000%26oauth_nonce%3D303860665718762%26oauth_signature_method%3DRSA-SHA1%26oauth_timestamp%3D1508243475%26oauth_version%3D1.0
                ]]>
            }, class Detail {
                name: Allowed OAuth Signature Base String 2
                value: <![CDATA[
                GET&https%3A%2F%2Fsandbox.api.mastercard.com%2Fmasterpass%2Fpaymentdata%2Fcc2467bd62e8a69cefdf4638083cabc2fe3ae43a&cartId%3D21345%26checkoutId%3D512135f929c448d0b930b537c1426ee2%26oauth_consumer_key%3Dx9CN7cXABdzeOpjVrAOa7v4pHhpkzLNTDcMEIOY60e2a0e46%2110e8bc47714141be983e984732a73a4c0000000000000000%26oauth_nonce%3D303860665718762%26oauth_signature_method%3DRSA-SHA1%26oauth_timestamp%3D1508243475%26oauth_version%3D1.0
                ]]>
            }]
        }
        extensionPoint: null
    }]
}
```

E o stacktrace:

```
org.eclipse.debug.core.DebugException: com.sun.jdi.ClassNotLoadedException: Type has not been loaded occurred while retrieving component type of array.
```

Imaginei que pudesse realmente estar com algum tipo de problema no sentido de não enviar o atributo _oauth_signature_, então debuguei até a classe de logging MasterCardSDKLoggingInterceptor e confirmei o que foi logado no console `Authorization: OAuth oauth_consumer_key="x9CN7cXABdzeOpjVrAOa7v4pHhpkzLNTDcMEIOY60e2a0e46%2110e8bc47714141be983e984732a73a4c0000000000000000",oauth_nonce="305763434476753",oauth_signature="FQYHPc87tyCK%2BZp9Qzu5aJ8P0xcCkHyNnC2SvbqN06n8sYaHHfeqgzovdFOcJCW%2BghTO5FIMSZzdYjtoTtygbJad4U%2Fg2rQU1%2Fy2Vtmj3MYEyPu1pxvU2KFk1X%2F46gdeOo7gqRpV54YLxgVipEi8kTp50U18NAIgLyBU3lviAyvkVm4%2BuFL5hftxMtmlXKPXmCCQ%2FMBZ%2Fa%2BX3FigCI1fdofQbZmir0Fqhpfh2G26PKg5elg5QntNiaOwJcyYLln7x6HhWFo2h9ZdTyCm6etX57gdRouCYHUPDTp0ujgd%2FbTargOMkSZ56z%2BOFL9da2eAQrboFPmqmtc7OMYmClaRNA%3D%3D",oauth_signature_method="RSA-SHA1",oauth_timestamp="1508245377",oauth_version="1.0",realm="eWallet"`: que existe um _oauth_signature_ e que por algum motivo está apresentando um erro. 

![image](https://user-images.githubusercontent.com/8642935/31666286-6df9f7e8-b32a-11e7-9884-8e3dbb7e6f11.png)

**Comment by marcoblos** [comment]
Eu encontrei a solução do problema enquanto eu escrevia a issue acima, mas achei justo registrá-la mesmo assim e postar a solução, mais alguém pode se beneficiar.

A resolução do problema é muito simples, foi um erro meu e não da API, ou do desenvolvedor que criou esse projeto de exemplo, faltou eu revisar todos os parâmetros setados em `App.makeConfigMap`, substituindo pelos parâmetros da minha conta.

Os parâmetros encontrados na página da Mastercard, dentro do projeto Masterpass são:

- consumerKey [link](https://developer.mastercard.com/masterpass/merchant/#/keyManagement2)
- password [link](https://developer.mastercard.com/masterpass/merchant/#/keyManagement2)
- alias [link](https://developer.mastercard.com/masterpass/merchant/#/keyManagement2)
- path (arquivo com extensão _.p12_, deve ficar na raiz do projeto, no mesmo nível do _pom.xml_) [link](https://developer.mastercard.com/masterpass/merchant/#/keyManagement2)
- checkoutId [link](https://developer.mastercard.com/masterpass/merchant/#/dashboard)

Para deixar um pouco mais claro:

### consumerKey, password, alias, path:

![image](https://user-images.githubusercontent.com/8642935/31669053-b54daefc-b332-11e7-902b-efb1fe3cc68f.png)

### checkoutId:

![image](https://user-images.githubusercontent.com/8642935/31669170-16d1c802-b333-11e7-96b2-fb1f8c5b6329.png)

Por mim a issue pode ser fechada, se restar alguma dúvida, volto a postar aqui.

**Comment by robson83** [comment]
Obrigado pelos comentários. Vou atualizar na documentação.
