### ISSUE TITLE
Quem cria o PaymentCode?

### ISSUE THREAD

**Issue by marcoblos** [MastercardBR/exemplo-masterpass-java-web#2]
No método `Api.performPostback ` é passado o parâmetro `paymentCode`.

Não encontrei onde esse código é gerado e a documentação do Masterpass não deixou muito clara essa informação.

Eu devo criar o `paymentCode` ou eu recebo essa informação durante a execução de alguma outra chamada à Api da masterpass?

Obrigado.

**Comment by robson83** [comment]
PaymentCode é o código de autorização que você recebe ao fazer sua transação no adquirente. Ao receber os dados do cartão, você manda para o adquirente e ele vai te retornar um código de 6 dígitos - chamado paymentCode.

Vou atualizar a documentação.

**Comment by marcoblos** [comment]
@robson83 ele vem dentro do objeto Request no callback?
Se a resposta da pergunta for sim, pego ele da mesma maneira que pego o `oauth_verifier` (`req.queryParams("oauth_verifier")`)?

Se a resposta for não, pego essa informação em qual objeto ou em qual passo dessa implementação de exemplo?

**Comment by robson83** [comment]
Ele não vem em lugar nenhum. Você precisa enviar isso para o seu adquirente, já que o Masterpass não tem nenhuma relação com ele. Para que fique claro, o fluxo funciona assim (para o caso do Standard checkout):

1- Cria o html e faz a chamada para a carteira do Masterpass;

2- Usuário faz login na carteira Masterpass, seleciona o cartão que quer usar e o endereço de entrega;

3- Masterpass retorna um callback para seu servidor;

4- Chamo o paymentData e recebo os dados do cartão de crédito. Se você tiver PCI, recebe todos os dados sem mascaramento; se não for PCI, recebe os dados, com mascaramento;

5- Envia os dados para seu adquirente (Cielo, Rede, Stone, Getnet, etc). Essa transação é idêntica a uma transação com cartão normal. O resultado dessa chamada no adquirente é uma transação autorizada ou negada e o postback serve para informar o Masterpass do resultado. Se for autorizada, você recebe um código de autorização de 6 dígitos - esse é o código que você precisa passar naquela chamada.

O Masterpass não interfere nessa relação com o adquirente, é um acordo que você deve ter. Vale lembrar que todo adquirente possui uma integração diferente.

**Comment by marcoblos** [comment]
Ótimo @robson83!
Obrigado pela explicação detalhada.
Estou seguindo exatamente esses passos , porém, fiquei com uma dúvida no passo 5... Se eu já estou utilizando o masterpass como forma de pagamento, qual a necessidade de eu envolver um adquirente?

Não sei se a pergunta é leiga demais, é a primeira vez que implemento um gateway de pagamento, não estou conseguindo visualizar a necessidade já que realizo toda transação através do masterpass, pelo o que consegui entender até aqui todas as minhas transações são realizadas através da API do Masterpass e o Masterpass que se preocupa em validar essas informações junto com os adquirentes, sendo assim, processando o pagamento para a minha aplicação e me retornando a informação de sucesso ou não através do callback.

Obrigado pela ajuda.

**Comment by robson83** [comment]
@marcoblos 

O Masterpass é uma carteira e não um gateway de pagamento. Fazendo um paralelo com o mundo real, tudo isso que o sample code faz é para "abrir a carteira do cliente" e pegar o cartão - no mundo real você pega seu cartão da carteira e coloca na máquina (que é de um adquirente). No mundo virtual, você precisa de um adquirente também para realizar a cobrança - alguns adquirentes não permitem que você integre diretamente, e te oferecem um gateway; outros adquirentes oferecem suas próprias APIs.

Logo, respondendo sua pergunta, você precisará do adquirente para realizar a cobrança no cartão. Depois de realizada a cobrança, você executa o callback e pronto.

**Comment by marcoblos** [comment]
@robson83, cara, tuas explicações foram esclarecedoras...
Mas depois de esclarecer algumas coisas, outras ficaram em dúvida. Sei que não é o assunto principal dessa issue, mas a mastercard tem um gateway de pagamento, o MPGS, correto?
Ontem durante o dia fui atrás de mais informações sobre o MPGS e acredito que ele seja realmente um gateway de pagamento, mas não encontrei uma documentação no mesmo local em que encontrei a documentação do masterpass e nem consegui criar um projeto do tipo MPGS (porque não existe na lista no momento de criar o projeto) no mesmo lugar que criei o projeto do masterpass (após fazer o login na página do desenvolvedor), então, procurei e encontrei o User Guide do MPGS e lá dizia que existe uma outra página de administração para essa API do Gateway, a qual eu não sei qual, não tenho acesso e não saberia também como logar (por não conhecer o MerchandID e o Password).

Principais dúvidas:

- O MPGS é um serviço de gateway para clientes finais? Por exemplo, tenho uma loja, quero processar pagamentos, logo, farei uso dessa API, aí processarei cartões de diversas bandeiras inclusive Mastercard.
- Encontrei na documentação descrito que não é a mastercard que me fornece o MerchantID e o Password para acesso a essa outra página de administração da API do MPGS, correto?
- Se é outra empresa que me fornece esses códigos, eu não deveria utilizar a API deles que por sua vez utiliza o MPGS, assim facilitando a minha implementação como client final do ciclo de disponibilização de pagamentos online?

Sei que são muitas perguntas e talvez não seja da tua área específica, mas meu chefe me passou algumas poucas informações e a recomendação inicial era implementar o masterpass para processar pagamentos (o que ficou claro que não é uma solução de pagamento) e após conversarmos sobre isso ele me passou o MPGS dizendo ser a solução de gateway que eu deveria utilizar, porém, não estou muito certo de que essa API seja o que eu preciso e estou encontrando dificuldades para encontrar a página de administração e realizar o cadastro para ter acesso as credenciais da API. Disso tudo fica uma única chateação: a propaganda da Mastecard e a sua documentação sobre alguns produtos não ajudam muito e deixam várias dúvidas em relação ao escopo de cobertura do produto, quem deve utilizar o produto e como utilizá-lo corretamente, espero que você entenda.

Mais uma vez, obrigado pela ajuda, até agora de todos os canais de suporte da Mastercard esse foi o mais rápido de todos, por isso todas essas perguntas por aqui.

**Comment by robson83** [comment]
@marcoblos não conheço muito do MPGS. Minha sugestão é procurar um adquirente e falar diretamente - o processo é relativamente simples. Se for para o Brasil, me informe que passo algum contato.

**Comment by marcoblos** [comment]
@robson83 desculpa pela demora na resposta, estivemos envolvidos em outros problemas... O pessoal aqui da empresa entrou em contato com a Mastercard e nos foi liberado as credenciais para utilização do MPGS, pelo o que consegui entender, através da TNSPay CNP API (não sei ao certo o que isso significa, permanece confuso algumas coisas). Essa implementação é para uma empresa da Irlanda.

Muito obrigado pela ajuda até aqui, de verdade!

Acredito que a issue possa ser fechada.

**Comment by robson83** [comment]
Ok.

Boa sorte por aí.
